### ISSUE TITLE
May you consider changing the way you connect hive to a configuration file?

### ISSUE THREAD

**Issue by zuoakang** [EDS-APHP/HiveQLKernel#16]

**Comment by Dubrzr** [comment]
Hi @zuoakang, yes for sure, I think we should keep the current way of connecting and add the configuration file way of connecting,  in case you want to simply change the server without having to edit the configuration file I have some user that find it more easy to change it directly in the kernel.

Do you want to contribute on this?

**Comment by bharatl** [comment]
@Dubrzr Can we completely remove current way of connecting and only support config file? Config file can be a json like below

`{
  "url": "hive://<kerberos-username>@<hive-host>:<hive-port>/<db-name>",
  "connect_args" : {
    "auth": "KERBEROS",
    "kerberos_service_name":"hive"
  },
  "pool_size": 5,
  "max_overflow": 10,
  "default_limit": 20,
  "display_mode": "be" 
}`

This will ensure connection details at once place and if there is any change in the configurations users can change the file and restart the kernel.

Let me know your thoughts and I would like to contribute on this.

**Comment by Dubrzr** [comment]
I'm not sure we should remove the possibility to configure the Hive connection from the kernel. Actually it makes sense to only have a single kernel for Hive and be able to connect to many different hive sources with this kernel.
Let's say I have two notebooks I am working on in parrallel that use the same hive kernel and use different hive servers, how can I manage that using only a single configuration file? It doesn't work, except if you install a different kernel for each hive server, which is not really easy...
I understand that it is really useful to have a configuration file so that you don't have to configure the connection each time you start a new hive lernel, but it should not remove the ability to connect to different source.
The solution could be that by default, when you start the kernel, it reads a configuration file at ~/.hiveql_kernel.conf, if it exists it uses it, else you have to configure the connection in the notebook. If you have a configuration file and want to connect to another hive server then the configuration in the notebook overwrite the one in the configuration file.

The proposition for the json is perfect :)

**Comment by bharatl** [comment]
@Dubrzr thanks for the clarification, will pick this up

**Comment by Dubrzr** [comment]
@bharatl awesome, let us know if you have any other thoughts about this or if you need help ;)
Thanks!

**Comment by Dubrzr** [comment]
I also was wondering if hiveql kernel could not be the start of a new more generalist kernel: an sqlalchemyKernel ! I mean, behind this kernel we only query a hive database using sqlalchemy, and we could think that with some work it can work with postgres, mysql, ... all sqlachemy compatible databases!
I think a sqlalchemyKernel would be awesome for a lot of persons, and I don't get why it doesn't already exists ahah. Next step ;)

**Comment by bharatl** [comment]
@Dubrzr @parisni raised [PR](https://github.com/EDS-APHP/HiveQLKernel/pull/19) 

implementation details:

- Current way of connecting to hive (cell with $$) takes precedence if present  else we check for config file 

- By default we read config file present at ~/.hiveql_kernel.json  (users home directory)

- There is also a provision for user to export path of the config file to variable HIVE_KERNEL_CONF_FILE  example export HIVE_KERNEL_CONF_FILE=<path_to_conf_file> and start the jupyter 

- Any changes to config file requires kernel to be restarted 

 This PR doesn't include changes to README and connection error string.
